#  #当Runner通过轮询检测到gitlab上有任务时，就会执行这个文件
#     #个人不是很熟yml的语法以及详细配置，都是找猫画虎的，求各位大神提出优化意见

#     stages:
#         - update

#     #更新代码并且安装依赖
#     update:     
#         stage: update
#         script:
#             - cd /app/test_node       #先进入到项目目录下，下面同理
#             - git pull
#             - sudo npm install
#             - cd /app/test_node
#             - npm run build
#             - cd /app/test_node/app-page
#             - cp -R /app/test_node/app-page/* /app
            
            
            
stages:
  - build
 
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
 
build:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build
    - cp -r dist/* /www
  tags: 
    - my-tag
    
       
